### ISSUE TITLE
Board 컴포넌트 margin/padding 설정이 무시됩니다

### ISSUE THREAD

**Issue by yuzzznh** [wafflestudio18-5/team5-frontend#39]
![image](https://user-images.githubusercontent.com/69066745/100330585-7d05aa80-3012-11eb-955a-68c77bf247dc.png)

화면 맨 오른쪽 끝과 add another list 버튼 사이에 10px의 간격을 주고 싶은데 margin으로도 padding으로도
심지어 빈 div로 색깔이 똑같은 너비 10px짜리 상자를 만들어서도
해결이 안 되는 것 같아 다시 또는 함께 보고자 issue에 남깁니다

구글링해보니 margin 상쇄가 나오던데 그 문제일 것 같기도 합니다

**Comment by woohm402** [comment]
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/39977696/100373795-ae9c6700-304e-11eb-8e11-92374a92429c.png">
해결했습니당

<img width="627" alt="image" src="https://user-images.githubusercontent.com/39977696/100373842-bc51ec80-304e-11eb-857b-002611fa2b27.png">
위 사진처럼 그냥 한 번 더 감싸주시면 됩니다.

<img width="196" alt="image" src="https://user-images.githubusercontent.com/39977696/100373904-d2f84380-304e-11eb-955e-1a32d1966b94.png">
혹시 css에도 어떻게 썼는지 궁금하실까봐 첨부합니다!


제가 따로 막 브랜치 파고 뭐 하고 하기에는 내용이 얼마 없어서, 그냥 다음 커밋때 반영해주시면 될 거 같아요오

**Comment by yuzzznh** [comment]
와 감사합니다!! 안그래도 card 스크롤바 위치랑 margin padding 마음에 안들어서 조금 고쳤는데 같이 해서 pr 올려둘게요 봐주셔서 감사해요
